// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for linux - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvaMcXA0yKh90BHdaD0Q4Bym6Pbc63Bk4',
    appId: '1:906239492495:web:dc5500a3b8acc70b098bfa',
    messagingSenderId: '906239492495',
    projectId: 'medicore-d0cbf',
    authDomain: 'medicore-d0cbf.firebaseapp.com',
    storageBucket: 'medicore-d0cbf.firebasestorage.app',
    measurementId: 'G-YCX50G0Z13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKrr6NpIQeOtVLfObJF6hYmqN2TE5heo',
    appId: '1:906239492495:android:f0f4af32e1cc91e1098bfa',
    messagingSenderId: '906239492495',
    projectId: 'medicore-d0cbf',
    storageBucket: 'medicore-d0cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCodHSagd-_WEjTbt7J536l-H_cmI6Udfo',
    appId: '1:906239492495:ios:588c91b073cc4d48098bfa',
    messagingSenderId: '906239492495',
    projectId: 'medicore-d0cbf',
    storageBucket: 'medicore-d0cbf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCodHSagd-_WEjTbt7J536l-H_cmI6Udfo',
    appId: '1:906239492495:ios:588c91b073cc4d48098bfa',
    messagingSenderId: '906239492495',
    projectId: 'medicore-d0cbf',
    storageBucket: 'medicore-d0cbf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvaMcXA0yKh90BHdaD0Q4Bym6Pbc63Bk4',
    appId: '1:906239492495:web:7f02674cc5e8e9a8098bfa',
    messagingSenderId: '906239492495',
    projectId: 'medicore-d0cbf',
    authDomain: 'medicore-d0cbf.firebaseapp.com',
    storageBucket: 'medicore-d0cbf.firebasestorage.app',
    measurementId: 'G-8LYTH4P39B',
  );
}
