// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYqGKKUgyUG1kD-jtpFXsuJ4zoHqP24M',
    appId: '1:862073087249:web:ecc1198f74d0f37c4d18b0',
    messagingSenderId: '862073087249',
    projectId: 'healthlens-5fc36',
    authDomain: 'healthlens-5fc36.firebaseapp.com',
    storageBucket: 'healthlens-5fc36.firebasestorage.app',
    measurementId: 'G-S8F615KW3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeg1w6R940dKYz0_znEOSEfEIJZISsTfc',
    appId: '1:862073087249:android:330aa0775d3573e04d18b0',
    messagingSenderId: '862073087249',
    projectId: 'healthlens-5fc36',
    storageBucket: 'healthlens-5fc36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS065NGFeu_zyH-eollFZX0OPxyMv7OAo',
    appId: '1:862073087249:ios:056d2d9b8a4d576f4d18b0',
    messagingSenderId: '862073087249',
    projectId: 'healthlens-5fc36',
    storageBucket: 'healthlens-5fc36.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS065NGFeu_zyH-eollFZX0OPxyMv7OAo',
    appId: '1:862073087249:ios:056d2d9b8a4d576f4d18b0',
    messagingSenderId: '862073087249',
    projectId: 'healthlens-5fc36',
    storageBucket: 'healthlens-5fc36.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCYqGKKUgyUG1kD-jtpFXsuJ4zoHqP24M',
    appId: '1:862073087249:web:f62d4706ee0242994d18b0',
    messagingSenderId: '862073087249',
    projectId: 'healthlens-5fc36',
    authDomain: 'healthlens-5fc36.firebaseapp.com',
    storageBucket: 'healthlens-5fc36.firebasestorage.app',
    measurementId: 'G-M9WXZEPCXL',
  );
}
